# Generated by `spoc stubs`. Do not edit; regenerate instead.
# ruff: noqa: I001

from collections.abc import Callable as _collections_abc_Callable
from typing import Any, Literal, overload

from shop.models import Product as _shop_models_Product
from shop.resources import SearchIndex as _shop_resources_SearchIndex
from spoc import Component, Framework, KindHandle

class _Root(Framework):
    @overload
    def resolve(
        self, identifier: Literal["models:shop.product"]
    ) -> Component[type[_shop_models_Product]]: ...
    @overload
    def resolve(
        self, identifier: Literal["resources:shop.search_index"]
    ) -> Component[_shop_resources_SearchIndex]: ...
    @overload
    def resolve(
        self, identifier: Literal["views:shop.find_product"]
    ) -> Component[_collections_abc_Callable[[str], str]]: ...
    @overload
    def resolve(
        self, identifier: Literal["views:shop.list_products"]
    ) -> Component[_collections_abc_Callable[[], dict[str, int]]]: ...
    @overload
    def resolve(
        self, identifier: Literal["views:shop.unannotated"]
    ) -> Component[_collections_abc_Callable[..., Any]]: ...
    @overload
    def resolve(self, identifier: str) -> Component[Any]: ...

framework: _Root
model: KindHandle
view: KindHandle
