# Generated by `spoc stubs`. Do not edit; regenerate instead.
# ruff: noqa: I001

from collections.abc import Callable as _collections_abc_Callable
from typing import Any, Literal, overload

from apps.shop.models import Product as _apps_shop_models_Product
from apps.shop.resources import SearchIndex as _apps_shop_resources_SearchIndex
from spoc import Component, Framework, KindHandle

class _ns_models_shop:
    product: Component[type[_apps_shop_models_Product]]

class _kind_models:
    shop: _ns_models_shop

class _ns_resources_shop:
    search_index: Component[_apps_shop_resources_SearchIndex]

class _kind_resources:
    shop: _ns_resources_shop

class _ns_views_shop:
    find_product: Component[_collections_abc_Callable[[str], str]]
    list_products: Component[_collections_abc_Callable[[], dict[str, int]]]
    unannotated: Component[_collections_abc_Callable[..., Any]]

class _kind_views:
    shop: _ns_views_shop

class _Objects:
    models: _kind_models
    resources: _kind_resources
    views: _kind_views

class _Root(Framework):
    @overload
    def resolve(
        self, identifier: Literal["models:shop.product"]
    ) -> Component[type[_apps_shop_models_Product]]: ...
    @overload
    def resolve(
        self, identifier: Literal["resources:shop.search_index"]
    ) -> Component[_apps_shop_resources_SearchIndex]: ...
    @overload
    def resolve(
        self, identifier: Literal["views:shop.find_product"]
    ) -> Component[_collections_abc_Callable[[str], str]]: ...
    @overload
    def resolve(
        self, identifier: Literal["views:shop.list_products"]
    ) -> Component[_collections_abc_Callable[[], dict[str, int]]]: ...
    @overload
    def resolve(
        self, identifier: Literal["views:shop.unannotated"]
    ) -> Component[_collections_abc_Callable[..., Any]]: ...
    @overload
    def resolve(self, identifier: str) -> Component[Any]: ...
    @property
    def objects(self) -> _Objects: ...

framework: _Root
model: KindHandle
view: KindHandle
