"""
The emitter: a manifest rendered as a type stub.

Pure text in, pure text out — no filesystem, no formatter, no process state.
Byte-stability comes from sorting (imports, and entries already in canonical
identifier order) and is then locked in by running the project's formatter over
the result in the adapter, not here.

The stub subclasses :class:`~spoc.Framework` and narrows ``resolve`` per
identifier. Permissive output keeps a trailing ``str`` overload, so identifiers
built at runtime still resolve and the override stays signature-compatible with
the base class. Strict output drops it, which is what turns a misspelled literal
into a type error — and, because dropping it narrows the parameter type, also
what makes the two suppression comments necessary. That trade is the whole
difference between the modes.
"""

from __future__ import annotations

import sys

from .extract import alias_for
from .manifest import Manifest

#: A comment, not a docstring: stub files follow typeshed conventions, where a
#: module docstring is a lint error (PYI021).
#:
#: Import *sections* are suppressed rather than matched. Which section a module
#: falls in is a property of the consuming project's linter configuration —
#: first-party versus third-party is theirs to define — so an emitter that
#: guessed would produce output that lints clean in one repository and fails in
#: the next, and whose bytes changed with the config. Everything else about the
#: file is still linted; only the section split is not ours to decide.
_HEADER = (
    "# Generated by `spoc stubs`. Do not edit; regenerate instead.\n# ruff: noqa: I001"
)

#: Emitted on the strict override because dropping the ``str`` fallback narrows
#: the parameter type relative to ``Framework.resolve``. Both checkers are named
#: explicitly so neither silently keeps reporting it.
_STRICT_SUPPRESSION = (
    "  # type: ignore[override]  # pyright: ignore[reportIncompatibleMethodOverride]"
)


def _is_stdlib(module: str) -> bool:
    return module.partition(".")[0] in sys.stdlib_module_names


def _import_lines(manifest: Manifest) -> list[str]:
    """Every import the stub needs, aliased and grouped the way isort groups.

    Grouping matters because the emitted stub is itself linted: ruff's import
    rules run over ``*.pyi``, so output that merely sorts deterministically but
    groups wrongly would generate a file that fails the project's own gate.
    """
    needed: set[tuple[str, str]] = set()
    for entry in manifest.entries:
        needed.update(entry.type_ref.imports)
    if manifest.handles:
        needed.add(("collections.abc", "Callable"))

    # Aliased imports take one line each while plain ones combine — isort's
    # `combine-as-imports = false` default, which ruff enforces over the very
    # file this emitter produces.
    statements: dict[str, list[str]] = {
        "stdlib": ["from typing import Any, Literal, overload"],
        "other": ["from spoc import Component, Framework, KindHandle"],
    }
    for module, name in needed:
        group = "stdlib" if _is_stdlib(module) else "other"
        statements[group].append(
            f"from {module} import {name} as {alias_for(module, name)}"
        )

    lines = sorted(statements["stdlib"])
    if lines and statements["other"]:
        lines.append("")
    lines.extend(sorted(statements["other"]))
    return lines


def _resolve_lines(manifest: Manifest, strict: bool) -> list[str]:
    """The body of the narrowed framework class."""
    signatures = [
        f'    def resolve(self, identifier: Literal["{entry.identifier}"])'
        f" -> Component[{entry.type_ref.expression}]: ..."
        for entry in manifest.entries
    ]
    if not strict:
        signatures.append(
            "    def resolve(self, identifier: str) -> Component[Any]: ..."
        )

    if not signatures:
        # Strict mode over a project with no components: nothing to narrow.
        return ["    pass"]
    if len(signatures) == 1:
        # A lone `@overload` is itself an error; emit it as a plain method.
        only = signatures[0]
        return [only + (_STRICT_SUPPRESSION if strict else "")]

    lines: list[str] = []
    for index, signature in enumerate(signatures):
        lines.append("    @overload")
        suffix = _STRICT_SUPPRESSION if strict and index == 0 else ""
        lines.append(signature + suffix)
    return lines


def emit(manifest: Manifest, strict: bool = False) -> str:
    """Render `manifest` as stub source text.

    Deterministic: the same manifest always produces the same bytes, because
    entries arrive in canonical identifier order and imports are sorted.
    """
    lines = [_HEADER, ""]
    lines.extend(_import_lines(manifest))
    lines.extend(["", "", "class _Root(Framework):"])
    lines.extend(_resolve_lines(manifest, strict))
    lines.extend(["", ""])
    lines.append(f"{manifest.framework_attribute}: _Root")

    lines.extend(f"{handle.attribute}: KindHandle" for handle in manifest.handles)
    return "\n".join(lines) + "\n"
