"""
The emitter: a manifest rendered as a type stub.

Pure text in, pure text out — no filesystem, no formatter, no process state.
Byte-stability comes from sorting (imports, and entries already in canonical
identifier order) and is then locked in by running the project's formatter over
the result in the adapter, not here.

The stub subclasses :class:`~spoc.Framework` and narrows ``resolve`` per
identifier. Permissive output keeps a trailing ``str`` overload, so identifiers
built at runtime still resolve and the override stays signature-compatible with
the base class. Strict output drops it, which is what turns a misspelled literal
into a type error — and, because dropping it narrows the parameter type, also
what makes the mypy suppression necessary. That trade is the whole difference
between the modes.
"""

from __future__ import annotations

import sys

from ..core.identity import escape_keyword
from .extract import alias_for
from .manifest import Manifest

#: A comment, not a docstring: stub files follow typeshed conventions, where a
#: module docstring is a lint error (PYI021).
#:
#: Import *sections* are suppressed rather than matched. Which section a module
#: falls in is a property of the consuming project's linter configuration —
#: first-party versus third-party is theirs to define — so an emitter that
#: guessed would produce output that lints clean in one repository and fails in
#: the next, and whose bytes changed with the config. Everything else about the
#: file is still linted; only the section split is not ours to decide.
_HEADER = (
    "# Generated by `spoc stubs`. Do not edit; regenerate instead.\n# ruff: noqa: I001"
)

#: Emitted on the strict override because dropping the ``str`` fallback narrows
#: the parameter type relative to ``Framework.resolve``.
#:
#: One comment, for mypy alone, and its placement is load-bearing: mypy honors
#: a suppression only on the line where it anchors ``[override]`` — the first
#: ``@overload`` decorator when there is one, otherwise the ``def`` itself —
#: while the formatter moves a comment trailing a long one-line signature onto
#: the closing ``...`` line, where mypy never reads it. So the comment rides
#: the decorator line, and the single-entry case pre-breaks its signature to
#: pin the comment to the ``def`` line (a comment inside the parentheses also
#: stops the formatter from re-joining the lines).
#:
#: pyright and ty report no incompatibility for this narrowing, so neither
#: gets a suppression — a comment no checker reads is a claim the conformance
#: gate cannot verify, and pyright flags unused ignores under
#: ``reportUnnecessaryTypeIgnoreComment``. A checker that *starts* reporting
#: fails the strict conformance leg, which is the detection point. Verified
#: against mypy 2.3.0, pyright 1.1.411, ty 0.0.66.
_STRICT_SUPPRESSION = "  # type: ignore[override]"


def _is_stdlib(module: str) -> bool:
    return module.partition(".")[0] in sys.stdlib_module_names


def _import_lines(manifest: Manifest) -> list[str]:
    """Every import the stub needs, aliased and grouped the way isort groups.

    Grouping matters because the emitted stub is itself linted: ruff's import
    rules run over ``*.pyi``, so output that merely sorts deterministically but
    groups wrongly would generate a file that fails the project's own gate.
    """
    needed: set[tuple[str, str]] = set()
    for entry in manifest.entries:
        needed.update(entry.type_ref.imports)
    if manifest.handles:
        needed.add(("collections.abc", "Callable"))

    # Aliased imports take one line each while plain ones combine — isort's
    # `combine-as-imports = false` default, which ruff enforces over the very
    # file this emitter produces.
    statements: dict[str, list[str]] = {
        "stdlib": ["from typing import Any, Literal, overload"],
        "other": ["from spoc import Component, Framework, KindHandle"],
    }
    for module, name in needed:
        group = "stdlib" if _is_stdlib(module) else "other"
        statements[group].append(
            f"from {module} import {name} as {alias_for(module, name)}"
        )

    lines = sorted(statements["stdlib"])
    if lines and statements["other"]:
        lines.append("")
    lines.extend(sorted(statements["other"]))
    return lines


def _resolve_lines(manifest: Manifest, strict: bool) -> list[str]:
    """The body of the narrowed framework class."""
    signatures = [
        f'    def resolve(self, identifier: Literal["{entry.identifier}"])'
        f" -> Component[{entry.type_ref.expression}]: ..."
        for entry in manifest.entries
    ]
    if not strict:
        signatures.append(
            "    def resolve(self, identifier: str) -> Component[Any]: ..."
        )

    if not signatures:
        # Strict mode over a project with no components: nothing to narrow.
        return ["    pass"]
    if len(signatures) == 1:
        # A lone `@overload` is itself an error; emit it as a plain method. In
        # strict mode there is no decorator line for the suppression, so the
        # signature is emitted pre-broken with the comment pinned to the `def`
        # line — mypy anchors there, and appending it to a one-line signature
        # would let the formatter carry it onto the `...` line instead.
        if not strict:
            return signatures
        entry = manifest.entries[0]
        return [
            f"    def resolve({_STRICT_SUPPRESSION}",
            f'        self, identifier: Literal["{entry.identifier}"]',
            f"    ) -> Component[{entry.type_ref.expression}]: ...",
        ]

    lines: list[str] = []
    for index, signature in enumerate(signatures):
        first = strict and index == 0
        lines.append("    @overload" + (_STRICT_SUPPRESSION if first else ""))
        lines.append(signature)
    return lines


def _navigation_lines(manifest: Manifest) -> list[str]:
    """The navigation surface as nested classes of typed members.

    Plain attributes on plain classes — the shape a checker resolves in one
    member lookup, at any size. That is the whole reason this exists beside the
    narrowed ``resolve``: an overload set makes a checker weigh every
    alternative on each call, and past a few thousand entries the ones a
    developer actually runs either crawl or stop answering.

    Emitted identically in both modes. There is nothing to loosen: an undeclared
    member is an error because it is absent, not because an overload was
    withheld, so the tree is strict by nature and needs no suppression.

    Class names are derived from the grammar segments they describe, prefixed
    and separated so ``_ns_models_shop`` cannot collide with a kind's own class
    however the segments are spelled.
    """
    navigation = manifest.navigation
    if not navigation:
        # Nothing registered: an empty marker class still lets `objects`
        # resolve, so a consumer's editor says "no members" rather than
        # "unknown attribute" on a project that has not registered yet.
        return ["class _Objects:", "    pass", "", ""]

    lines: list[str] = []
    for kind, namespaces in navigation.items():
        for namespace, entries in namespaces.items():
            lines.append(f"class _ns_{kind}_{namespace}:")
            lines.extend(
                f"    {escape_keyword(entry.object_name)}: "
                f"Component[{entry.type_ref.expression}]"
                for entry in entries
            )
            lines.extend(["", ""])
        lines.append(f"class _kind_{kind}:")
        lines.extend(
            f"    {escape_keyword(namespace)}: _ns_{kind}_{namespace}"
            for namespace in namespaces
        )
        lines.extend(["", ""])

    lines.append("class _Objects:")
    lines.extend(f"    {escape_keyword(kind)}: _kind_{kind}" for kind in navigation)
    lines.extend(["", ""])
    return lines


def emit(manifest: Manifest, strict: bool = False) -> str:
    """Render `manifest` as stub source text.

    Deterministic: the same manifest always produces the same bytes, because
    entries arrive in canonical identifier order and imports are sorted.
    """
    lines = [_HEADER, ""]
    lines.extend(_import_lines(manifest))
    lines.extend(["", ""])
    lines.extend(_navigation_lines(manifest))
    lines.append("class _Root(Framework):")
    lines.extend(_resolve_lines(manifest, strict))
    lines.append("    @property")
    lines.append("    def objects(self) -> _Objects: ...")
    lines.extend(["", ""])
    lines.append(f"{manifest.framework_attribute}: _Root")

    lines.extend(f"{handle.attribute}: KindHandle" for handle in manifest.handles)
    return "\n".join(lines) + "\n"
